# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('reg_date', models.DateTimeField(verbose_name='Date of registration')),
            ],
        ),
    ]
