# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='surname',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
