# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_auto_20170615_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='surname',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
    ]
